- name: create app virtualenv with Python2.7.11
  command: virtualenv --python=/opt/bin/python2.7 /var/opt/wsgi/amphora/env
  args:
    creates: /var/opt/wsgi/amphora/env
  become: yes
  become_user: amphora
- name: make sure pip is up to date
  pip:
    name: pip
    state: latest
    virtualenv: /var/opt/wsgi/amphora/env
  become: yes
  become_user: amphora
- name: install python dependencies for app
  pip:
    requirements: /var/opt/wsgi/amphora/amphora/requirements.txt
    virtualenv: /var/opt/wsgi/amphora/env
  become: yes
  become_user: amphora
- name: make sure that gunicorn is installed in the app virtualenv
  pip:
    name: gunicorn
    virtualenv: /var/opt/wsgi/amphora/env
  become: yes
  become_user: amphora
